apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
stringData:
  SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
  NAME: "tododb"
  USER: "todo_user"
  PASSWORD: "todo_pass"
  HOST: "mysql-0.mysql.mysql.svc.cluster.local"