apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
stringData:
  MYSQL_DATABASE: "tododb"
  MYSQL_ROOT_PASSWORD: "my-secret-pw"
  MYSQL_USER: "todo_user"
  MYSQL_PASSWORD: "todo_pass"